[package]
name = "pulumi_wasm_example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pulumi_wasm_random = {version = "=4.15.0-0.0.0-NIGHTLY-4261dfd", registry = "cloudsmith"}
pulumi_wasm_rust = {version = "=0.0.0-NIGHTLY-4261dfd", registry = "cloudsmith"}
anyhow = "1.0.86"