[workspace]
resolver = "3"
members = [
    "native",
    "random",
    "wasm"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
pulumi_random = { path = "random" }

pulumi_gestalt_rust = "0.0.2"
anyhow = "1.0.95"
bon = "3.3.1"
pulumi_gestalt_build = "0.0.2"
