set windows-shell := ["pwsh.exe", "-c"]
binary := "pulumi_gestalt_wasm_runner"
wasm := "../target/wasm32-wasip2/debug/pulumi_gestalt_example_wasm.wasm"

run:
    cargo build --target wasm32-wasip2
    {{binary}} run --debug "{{wasm}}"

install-requirements:
    cargo binstall -y pulumi_gestalt_wasm_runner@0.0.1
    pulumi plugin install language gestalt "0.0.1" --server github://api.github.com/andrzejressel/pulumi-gestalt

[windows]
local-test:
    #!pwsh
    Set-StrictMode -Version Latest
    $ErrorActionPreference = "Stop"
    $PSNativeCommandUseErrorActionPreference = $true

    $env:PULUMI_CONFIG_PASSPHRASE=" "
    pulumi destroy -y
    pulumi up -y