[package]
name = "pulumi_random"
version.workspace = true
edition.workspace = true

[dependencies]
pulumi_gestalt_rust.workspace = true
wit-bindgen.workspace = true
bon.workspace = true

[build-dependencies]
pulumi_gestalt_build.workspace = true