[package]
name = "pulumi_random"
version = "0.1.0"
edition = "2021"

[dependencies]
pulumi_gestalt_rust.workspace = true
wit-bindgen.workspace = true
bon.workspace = true

[build-dependencies]
pulumi_gestalt_build.workspace = true