set windows-shell := ["pwsh.exe", "-c"]
binary := "../target/debug/pulumi_gestalt_example_native"

run:
    cargo build
    {{binary}}

install-requirements:
    pulumi plugin install language gestalt "25.2.14-9374348" --server github://api.github.com/andrzejressel/pulumi-gestalt-releases

[windows]
local-test:
    #!pwsh
    Set-StrictMode -Version Latest
    $ErrorActionPreference = "Stop"
    $PSNativeCommandUseErrorActionPreference = $true

    $env:PULUMI_CONFIG_PASSPHRASE=" "
    pulumi destroy -y
    pulumi up -y