name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      RUST_BACKTRACE: "full"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: protoc --version
      - run: brew install pulumi
        if: runner.os == 'macOS'
      - run: pulumi version
      - run: pulumi login --local
      - uses: Swatinem/rust-cache@v2
      - name: Install requirements
        run: just install-requirements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install pulumi wasm language
        run: pulumi plugin install language wasm "0.0.0-NIGHTLY-886e811" --server github://api.github.com/andrzejressel/pulumi-wasm
      - name: Run
        run: |
          pulumi stack init test
          pulumi stack select test
          pulumi up -y
          pulumi stack output --json
        env:
          PULUMI_CONFIG_PASSPHRASE: ""